config/routes.rb
Rails.application.routes.draw do
  resources :pets
  get 'owners/ownerpets', to: 'owners#ownerpets'
  resources :owners
#  post 'owners/:id/edit', to: ''
  # get 'owners/new', to: 'owners#new'
  # post 'owners', to: 'owners#create'
  #
  # # get 'owners/:id', to: 'owners#show'
  # get 'owners/:id/edit', to: 'owners#edit'
  # get 'owners/update'
  # get 'owners/destroy'

  #  resources :owners, only: [:index, :show, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :pets
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  def self.owner_pets
    Owner.select do |owner|
      owner.pets.count >= 1
    end
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :owner
  validates :name, presence: true
  validate :validate_species

  def validate_species
    array = ["cat", "bird", "dog", "fish"]
    if array.include?(self.species) == false
      errors.add(:species, "is this even a real pet?")
    end

  end
end
# validates :species, inclusion: {in: ["cat", "bird", "dog", "fish"]}

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end

  def show
    @owner = Owner.find(params[:id])

  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.create(owner_params)
    redirect_to owner_path
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])
    @owner.update(owner_params)
    redirect_to @owner
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy
    redirect_to owners_path
  end

  def ownerpets
    @owners = Owner.owner_pets 
  end

  private

    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :age, :email)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.create(pet_params)
    if @pet.valid?
      flash[:message] = "Pet Created Successfully"
      redirect_to @pet
    else
      flash[:message] = "#{@pet.errors.full_messages[0]}"
      render :new
    end

  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private
   def pet_params
     params.require(:pet).permit(:name, :species, :owner_id)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/edit.html.erb
<h1>Edit Owner Form</h1>
<%= form_for @owner do |f| %>
<%= f.label 'First Name' %>
<%= f.text_field :first_name %><br>
<%= f.label 'Last Name' %>
<%= f.text_field :last_name %><br>
<%= f.label 'Your age' %>
<%= f.number_field :age %><br>
<%= f.label 'Email' %>
<%= f.text_field :email %><br>
<%= f.submit "Save" %>

<% end %>

app/views/owners/index.html.erb
<h1>All Owners</h1>
<ul>
  <%@owners.each do |owner|%>
    <li>
      <%= link_to owner.full_name, owner_path(owner) %>
    </li>
  <%end%>
</ul>

app/views/owners/new.html.erb
<h1>New Owner Form</h1>

<%= form_for @owner do |f| %>
  <%= f.label 'First Name' %>
  <%= f.text_field :first_name %><br>
  <%= f.label 'Last Name' %>
  <%= f.text_field :last_name %><br>
  <%= f.label 'Your age' %>
  <%= f.number_field :age %><br>
  <%= f.label 'Email' %>
  <%= f.text_field :email %><br>
  <%= f.submit "Create" %>
<% end %>

app/views/owners/ownerpets.html.erb
<ul>
    <%@owners.each do |owner|%>
      <li><%=owner.full_name%></li>
    <%end%>
</ul>

app/views/owners/show.html.erb
<h1> This is <%=@owner.full_name %> page!</h1>
<%= link_to "Edit", edit_owner_path, method: :get %>
<%= link_to "Delete", @owner, method: :delete %>

app/views/pets/edit.html.erb
<h1>Pets#edit</h1>


<%=form_for @pet do |f|%>
  <%=f.label :name%>
  <%=f.text_field :name%>
  <%=f.label :species%>
  <%=f.text_field :species%>
  <%=f.collection_select(:owner_id, Owner.all, :id, :full_name)%>
  <%=f.submit "Submit Edit"%>
<%end%>

app/views/pets/index.html.erb
<h1>Pets#index</h1>
<p>Find me in app/views/pets/index.html.erb</p>

app/views/pets/new.html.erb
<% if flash[:message] %>

<h1><%=flash[:message]%></h1>

<%end%>

<h1>New Pet</h1>
<%=form_for @pet do |f|%>
  <%=f.label :name%>
  <%=f.text_field :name%>
  <%=f.label :species%>
  <%=f.text_field :species%>
  <%=f.collection_select(:owner_id, Owner.all, :id, :full_name)%>
  <%=f.submit "Create"%>
<%end%>

app/views/pets/show.html.erb
<h1>This is a <%=@pet.species%>, named <%=@pet.name%>!</h1>
<%= link_to "Edit", edit_pet_path, method: :get %>
<%= link_to "Delete", @pet, method: :delete %>